#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=ACMR -- 'src/**/*.ts' 'test/**/*.ts')

if [ -z "$files" ]; then
  exit 0
fi

echo "$files" | while IFS= read -r file; do
  ./node_modules/.bin/prettier --write --ignore-unknown "$file"
  git add "$file"
done
